$(document).ready(function(e){if($('#landing_form').length){$('#landing_form')[0].reset();}
    $('#landing_form').submit(function(){$(this).ajaxSubmit({dataType:"json",success:function(response){if(response.status=="OK"){document.location=response.success;}
        if(response.status=="ERROR"&&response.error.class_name=="ExUploadResource"){$('.jq-file__name').css('border-color','#f2f2f2');var length=response.error.number.length;element=null;for(var i=0;i<length;i++){$('.jq-file__name').eq(response.error.number[i]).css('border',' 2px solid rgb(252, 98, 95)');}
            $('#fileExUploadResource').show();$(".finish").rm_preloader();}else{jQuery('.file-error').hide();}
        if(response.status=="ERROR"&&response.error.class_name=="ExValidateFails"){}else if(response.status=="ERROR"&&response.error.class_name=="ExInvalidPromoCode"){$().landingConfirmation("Указанный промо-код не существует, продолжить размещение заказа без указания промо-кода?",function(){$("#promo_code").val("");$("#landing_form").submit();return false;},function(){$(".finish").rm_preloader();return false;});}}});return false;});if([1,4,28,9,53,7,10,3,29,121].indexOf(parseInt($('#type').val()))!=-1&&$('#phone').val().length>=4){$('#pers_m').val('1');}else{$('#pers_m').val('0');}
    $('#phone').bind("keyup keydown",function(e){if([1,4,28,9,53,7,10,3,29,121].indexOf(parseInt($('#type').val()))!=-1&&$('#phone').val().length>=4){$('#pers_m').val('1');}else{$('#pers_m').val('0');}});$('#type').change(function(){if([1,4,28,9,53,7,10,3,29,121].indexOf(parseInt($(this).val()))!=-1&&$('#phone').val().length>=4){$('#pers_m').val('1');}else{$('#pers_m').val('0');}});$('.h_sign').click(function(e){$('#login').val('');$('#password').val('');$('.popup_sign').show();$('#login').focus();return false;});$("#manager").change(function(){var display=$(this).is(":checked")?"table":"none";$("#phoneField").css("display",display);});$("a[rel='checkbox']").checkboxStyle();$("#type").personalManager();$('.popup_shadow').click(function(){if($(this).parent().attr('class')!='popup_preload popup'){$(this).parent().hide();}
        return false;});$('#password, #login').keypress(function(e){if(e.which==13){$('#enter-button').trigger('click');}});$('#enter-button').click(function(){var hash={login_email:$("#login").val(),login_password:$("#password").val()};$.post("/ajax/login-remember",hash,function(response){if(response.status=="ERROR"){if(response.error.class_name=='ExUserFullBlocked')
    {return alert("Ваш аккаунт заблокирован или удален. Для его восстановления обратитесь к Администрации проекта.");}else{return alert("Пользователь с таким адресом email и паролем не найден");}}
        document.location=response.redirect;},"json");return false;});$('.has_pointer, #get_prise').click(function(){var element=$('.has_pointer');element.stop(false,false)
        $('html,body').animate({scrollTop:100},'slow');});$('#volume_from').ForceNumericOnly();$('#volume_to').ForceNumericOnly();$('#video_watch').click(function(){$('.popup_video').show();});$('.close_popup, #author_selector').click(function(){$(this).parents('.popup').hide();});$('input[type=text], input[type=file], select').styler();$("#phone_country_code").initPhonesStyler($("#phone"));$("#subject").subjectAutocomplete({top_delta:46,step:66});$("#term_date").datepicker(calendar_options);$("#term_date").keypress(function(){return false;})
    $(".show_more .sm_link").click(function(){$(".additional").toggle(function(){});$(".show_more").toggleClass("opened");return false;});$('.reviews_block').fadeIn('slow');$('.author_slider').bxSlider({minSlides:3,maxSlides:5,slideWidth:149,slideMargin:40,pager:true,useCSS:false,controls:false,infiniteLoop:false,preventDefaultSwipeX:0});$('.author_slider').fadeIn('slow');$('.show_pay_popup').click(function(e){if($(this).parent().hasClass("visible")){$(this).parent().removeClass("visible");return false;}
    else{$('.pay_type').each(function(index,element){$(this).removeClass("visible");});$(this).parent().addClass("visible");return false;}});$('.close_popup').click(function(e){return false;});$('.finish').live('click',function(){self=$(this);$.post('/ajax/new-order/valid/landing/form/',{email:$('#email').val(),name:$('#name').val(),volume_to:$('#volume_to').val(),volume_from:$('#volume_from').val(),title:$('#title').val(),type:$('#type').val(),subject:$('#subject').val(),term_date:$('#term_date').val()},function(response){$(".finish").preloader();$('.error').removeClass('error');$('.error_msg').hide();if(response.status=='OK'){$('#landing_form').submit();}else{if(response.status=="ERROR"&&response.error.class_name=="ExValidateFails"){$(response.error.fields).showErrorsNewLanding({field_css:"error"});$(".finish").rm_preloader();}else if(response.status=="ERROR"&&response.error.class_name!="ExValidateFails"){}
        $('.popup_find_price').remove();}},"JSON");return false;});$('.author').click(function(e){$('.popup_author_chose, .popup_shadow').show();var a=$('body').scrollTop();return false;});$('.free-call-hint-main').click(function(){window.open('http://issa.mangotele.com/widget/MTE2Mjk1','mangotele_widget','width=238,height=350,resizable=no,toolbar=no,menubar=no,location=no,status=no');return false;return false;});$('.inputs .del_file').live('click',function(){main=$(this);if($('input[name=order_resource\\[\\]]').length<2){main.parent().children('span').children('.jq-file__name').html('');main.parent().children('span').children('input[type=file]').val('');}else{$(this).parent().remove();if($('.jq-file__name').css('border-color')=='rgb(242, 242, 242)'){$('#fileExUploadResource').hide();}}
        return false;});$('.close_popup').live('click',function(){$('.popup_find_price').remove();return false;});$('.inputs .add_more').live('click',function(){html='<div><input type="file" class="inp-file" value="Обзор" name="order_resource[]"/><a href="#" class="del_file">Удалить</a></div>';$(this).parent().append(html);$('input:file').styler();return false;});$('body').click(function(){$('.pay_type').attr('class','pay_type');})
    $(window).scroll(function(){if($(window).scrollTop()>=600&&!$('.bot_link').hasClass("visible")){$('.bot_link').addClass("visible");$('.bot_link').stop().animate({bottom:"0px"},1000);};if($(window).scrollTop()<250&&$('.bot_link').hasClass("visible")){$('.bot_link').removeClass("visible");$('.bot_link').stop().animate({bottom:"-85px"},1000);};});$('.jq-selectbox__dropdown').css('height',parseInt($(window).height())-(parseInt($(window).height())/100)*40);$('.jqselect').click(function(){$('.jq-selectbox__dropdown').css('height',parseInt($(window).height())-(parseInt($(window).height())/100)*40);});if($(".ac_odd, .ac_even").length>0){$('.pops').show();}else{$('.pops').hide();}
    $('#subject').keyup(function(){if($(".ac_odd, .ac_even").length>0){$('.pops').show();}else{$('.pops').hide();}});$(".right .pops .suglist").click(function(){$('.pops').hide();});$(".jqselect").css('z-index',1);$(".inp_line .whatis, .checkbox .whatis").click(function(){return false;});$(".inp_line .whatis, .checkbox .whatis").tipsy({html:true,opacity:1});});