$(function(){var autocompleteRequest={query:null,abort:function(){if(this.query){this.query.abort();}}}
$.fn.extend({subjectAutocomplete:function(options){$(this).attr("autocomplete","off");options=options||{top_delta:30,step:56,suggest_top:359,suggest_bottom:598};$.fn.extend({autocompletePosition:function(index){if(index>=$(".subject-autocomplete div").length||index<0){return false;}
$(".subject-autocomplete div.hover").removeClass("hover");$(".subject-autocomplete div:eq("+index+")").addClass("hover");if(parseInt($(".subject-autocomplete div.hover").offset().top)<parseInt($(".subject-autocomplete").offset().top)){$(".subject-autocomplete").scrollTop($(".subject-autocomplete").scrollTop()-options.step);}
if(parseInt($(".subject-autocomplete div.hover").offset().top)>$(".subject-autocomplete").offset().top+$(".subject-autocomplete").height()){$(".subject-autocomplete").scrollTop($(".subject-autocomplete").scrollTop()+options.step);}},pValue:function(){var value=$(this).val();value=value.replace(/^\s+/g,"");value=value.replace(/\s+/g," ");return value;},subjectHandler:function(e){if($(this).val().length==0){autocompleteRequest.abort();$(".subject-autocomplete").remove();return true;}
if(e.keyCode==37||e.keyCode==39){return true;}
if(e.keyCode==38){var index=$(".subject-autocomplete div.hover").index()-1;$().autocompletePosition(index);return false;}
if(e.keyCode==40){var index=$(".subject-autocomplete div.hover").index()+1;$().autocompletePosition(index);return false;}
var self=this;if(e.keyCode==13){if($(".subject-autocomplete div.hover p").length>0){$(self).val($(".subject-autocomplete div.hover p").text());}
$(".subject-autocomplete").remove();return false;}
$(".subject-autocomplete").remove();autocompleteRequest.abort();autocompleteRequest.query=$.post("/ajax/find-subject/",{q:$(this).pValue()},function(response){if(response.status=="ERROR"||response.result.length==0){return false;}
var html='<div class="subject-autocomplete">';$(response.result).each(function(i,item){var items=item.split("::");html+='<div><p>'+items[0]+'</p><span>'+items[1]+'</span></div>';});html+='</div>';$(document.body).append(html);$(".subject-autocomplete div").hover(function(){$(this).addClass("hover_mouse")},function(){$(this).removeClass("hover_mouse")});$(".subject-autocomplete").css("top",$(self).offset().top+options.top_delta);$(".subject-autocomplete").css("left",$(self).offset().left);$(".subject-autocomplete").mouseover(function(){$(self).unbind("blur");});$(".subject-autocomplete").mouseout(function(){$(self).blur(function(){$(".subject-autocomplete").remove();});});$(".subject-autocomplete div").click(function(){$(self).val($(this).children("p").text());$(".subject-autocomplete").remove();$(self).blur(function(){$(".subject-autocomplete").remove();});});},"json");}});$(this).keypress(function(e){if(e.keyCode==13){return false;}});$(this).keydown(function(e){if(e.keyCode==9){$(".subject-autocomplete").remove();return true;}
if(e.keyCode==13){return false;}});$(this).blur(function(){$(".subject-autocomplete").remove();});$(this).keyup($().subjectHandler);$(this).focus($().subjectHandler);}})});